### ISSUE TITLE
sprite atlas issue

### ISSUE THREAD

**Issue by llluxuryman** [KaarinGaming/TowerDefenceTutorial#1]
Hi Kaarin, I started making a game with your tutorial and faced with this issue on EPISODE #2 - IMAGES.
I changed your code from:    .getResourceAsStream("spriteatlas.png");
                                      to:    .getResourceAsStream("/res/spriteatlas.png");
                                      
Then I faced with a lot of other problems with code and decided to donload your full project, but it throws me this again. Recoding like I said above does'n help. Please HELP ME!!!!! Your tutorial is the most useful and unique.

HERE IS THE CONSOLE LOG WHEN I STARTING THE PROJECT

Exception in thread "main" java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1356)
	at helpz.LoadSave.getSpriteAtlas(LoadSave.java:35)
	at managers.TileManager.loadAtalas(TileManager.java:70)
	at managers.TileManager.<init>(TileManager.java:27)
	at main.Game.initClasses(Game.java:58)
	at main.Game.<init>(Game.java:36)
	at main.Game.main(Game.java:95)

**Comment by YohannesTz** [comment]
Is there a fix to this? I am facing the same issue too.

**Comment by YohannesTz** [comment]
Ah, if you are using Eclipse, I think you need to add the ``src`` folder to the build path. to do that, right click on the project => hover on Build Path => Configure build path.

![Click on add folder](https://i.imgur.com/92MAvPd.png?1)

![check on res folder](https://i.imgur.com/q9xninz.png?1)

it should work.
